---
###
# provision-00-common playbook
##
# Perform basic OS configuration
##

# Ignore SSH host key checking on first run
# Useful when VMs have just been created with Terraform and host keys
#  are not yet in your ~/.ssh/known_hosts file
#
# All environments except localhost

- hosts: docker:!localhost:!test
  gather_facts: no
  tasks:
    - name: Check known_hosts for each hostname
      command: ssh-keygen -F {{ hostvars[inventory_hostname]['ansible_host'] }}
      delegate_to: localhost
      register: has_entry_in_known_hosts_file
      changed_when: false
      ignore_errors: yes
    - debug:
        var: has_entry_in_known_hosts_file
    - name: Ignore host key on first run
      when: has_entry_in_known_hosts_file.rc == 1
      set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'



# Basic OS config
#
# All environments except localhost
- hosts: docker:!localhost:!test
  tasks:
    - name: Set timezone to Etc/UTC
      become: True
      timezone:
        name: Etc/UTC

    - name: Add SSH authorized_keys
      become: True
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ item }}"
      with_items: "{{ docker_authorized_ssh_keys }}"

    - name: Update /etc/hosts
      become: true
<<<<<<< HEAD
      blockinfile:
          path: /etc/hosts
          create: yes
=======
      with_items: groups['dockerswarm_manager']
      blockinfile:
          path: /etc/hosts
          create: yes
          marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
>>>>>>> a31b172891aa3cebd668368c93196e8e459da004
          block: |
            {% for host in ansible_play_batch %}
            {{ hostvars[host]['ansible_default_ipv4']['address'] }}   {{ host }}
            {% endfor %}
            
<<<<<<< HEAD
    - name: Update /etc/hosts with registry.app.local
      become: true
      blockinfile:
          path: /etc/hosts
          marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
          block: |

            {{ hostvars[item].ansible_default_ipv4.address }} registry.app.local

      with_items: "{{groups.dockerswarm_manager}}"
    
=======
            hostvars[item]['ansible_default_ipv4']['address'] registry.app.local

>>>>>>> a31b172891aa3cebd668368c93196e8e459da004

    # ADD YOUR OWN TASKS HERE
    #
